name: spp_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gopay.png
    - assets/ovo.png
    - assets/dana.png
    - assets/bca.png
    - assets/mandiri.png
    - assets/bri.png
    - assets/bni.png
    - assets/citibank.png
    - assets/linkaja.png
    
    
